### ISSUE TITLE
P3 Act 3 Architec - Arcángel GC

### ISSUE THREAD

**Issue by ArcangelGC** [SistemasTecTlaxiaco/actividad-3-practica-architect-ArcangelGC#1]
[P3 - Arcangel GC.pdf](https://github.com/user-attachments/files/16839924/P3.-.Arcangel.GC.pdf)

**Comment by AricelCastro** [comment]
20/20 cumple con todos los criterios conforme a la rúbrica

**Comment by josealfredo79** [comment]
bien hecho y revisado...
